# Generated by Django 4.2.4 on 2026-03-31 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsAdmin', '0002_otpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_address', models.CharField(max_length=255)),
                ('buyer_names', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('out_for_signature', 'Waiting on buyers signatures'), ('signed_by_buyers', 'Offer ready to send'), ('executed', 'Fully Executed'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('docusign_envelope_id', models.CharField(blank=True, max_length=100, null=True)),
                ('draft_pdf_url', models.URLField(blank=True, max_length=500, null=True)),
                ('signed_pdf_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
