# Generated by Django 4.2.4 on 2026-07-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsAdmin', '0003_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fub_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
