# Generated by Django 4.2.4 on 2026-08-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsAdmin', '0004_customuser_fub_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fub_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('out_for_signature', 'Waiting on buyers signatures'), ('signed_by_buyers', 'Offer ready to send'), ('fully_executed', 'Fully Executed'), ('cancelled', 'Cancelled')], default='draft', max_length=50),
        ),
    ]
