# Generated by Django 4.2.4 on 2026-08-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsAdmin', '0005_customuser_fub_refresh_token_deal_buyer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='fub_synced',
            field=models.BooleanField(default=False),
        ),
    ]
