# Generated by Django 4.2.4 on 2026-08-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsAdmin', '0006_deal_fub_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
