# Generated by Django 4.2.4 on 2026-09-02 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsAdmin', '0007_deal_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(default='other', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('direction', models.CharField(choices=[('received', 'Received'), ('sent', 'Sent')], default='received', max_length=10)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('received', 'Received'), ('out_for_signature', 'Out for signature'), ('signed', 'Signed'), ('rejected', 'Rejected')], default='received', max_length=30)),
                ('docusign_envelope_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf_key', models.CharField(blank=True, max_length=500, null=True)),
                ('signed_pdf_key', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='AccountsAdmin.deal')),
            ],
        ),
    ]
