# Generated by Django 4.2.4 on 2026-09-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsAdmin', '0008_dealdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fub_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fub_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='draft_pdf_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='signed_pdf_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
