# Generated by Django 4.2.4 on 2026-09-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsAdmin', '0009_alter_customuser_fub_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='acceptance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='checklist_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='deal',
            name='form_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Team Admin'), ('tc', 'Transaction Coordinator'), ('agent', 'Agent')], default='agent', max_length=20),
        ),
    ]
