"""
Django settings for ApexIntegrationsAPI project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    'www.apexintegrations.ai',
    '127.0.0.1',
    'localhost',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'AccountsAdmin'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ApexIntegrationsAPI.urls'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ApexIntegrationsAPI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Postgres in production (set DATABASE_URL in .env, e.g. from Neon/RDS:
#   postgresql://user:pass@host/dbname?sslmode=require
# ). SQLite remains the zero-config fallback for local development only —
# it has taken the live API down twice with file locks and is NOT for prod.
_DATABASE_URL = os.environ.get('DATABASE_URL', '')
if _DATABASE_URL:
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(
            _DATABASE_URL,
            conn_max_age=600,          # persistent connections per worker
            conn_health_checks=True,   # recover cleanly from dropped conns
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {'timeout': 25},
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 2. Where Django should look for your custom files (like your PDF)
# Since you created a 'static' folder right in your base directory, we add it here.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'AccountsAdmin.CustomUser'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
# Never let a stalled SMTP connection hang a login request (and its worker).
EMAIL_TIMEOUT = 15
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Real Estate App <no-reply@apexintegrations.ai>')

# Pusher (real-time)
PUSHER_APP_ID = os.environ.get('PUSHER_APP_ID', '')
PUSHER_KEY = os.environ.get('PUSHER_KEY', '')
PUSHER_SECRET = os.environ.get('PUSHER_SECRET', '')
PUSHER_CLUSTER = os.environ.get('PUSHER_CLUSTER', 'us2')

# Dev/App-Store-review OTP bypass. OFF by default; set OTP_DEV_BYPASS=True only
# on non-production (e.g. the demo server). Gates the 000000 login backdoor.
OTP_DEV_BYPASS = os.environ.get('OTP_DEV_BYPASS', 'False').lower() == 'true'

# AWS S3 Configuration
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-2')
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_ADDRESSING_STYLE = 'virtual'
AWS_S3_ENDPOINT_URL = 'https://s3.us-east-2.amazonaws.com'
FUB_CLIENT_ID = os.environ.get('FUB_CLIENT_ID', 'fallback_id_if_missing')
FUB_CLIENT_SECRET = os.environ.get('FUB_CLIENT_SECRET', 'fallback_secret_if_missing')
# Optional: FUB system key (X-System-Key) — enables HMAC verification of inbound webhooks.
FUB_SYSTEM_KEY = os.environ.get('FUB_SYSTEM_KEY', '')

# --- MLS (RESO Web API) — broker back-office lookup ---
# ONE company-level credential (every app user is a licensed agent). Set these in
# .env on the server; never commit them. If unset, the MLS endpoint returns 503.
MLS_API_BASE_URL = os.environ.get('MLS_API_BASE_URL', '')        # e.g. https://api.<your-mls>.com/reso/odata
MLS_API_TOKEN = os.environ.get('MLS_API_TOKEN', '')             # server bearer token from your MLS/vendor
MLS_LISTING_ID_FIELD = os.environ.get('MLS_LISTING_ID_FIELD', 'ListingId')  # RESO filter field

# --- Brokerage identity stamped onto generated RE-21 contracts ---
# Source of truth is the DATABASE: the authenticated agent (CustomUser) and
# their Organization (see apply_agent_identity in views.py). These env values
# are only a FALLBACK for unauthenticated previews / before orgs are populated.
# Blank until configured (never a hardcoded competitor name).
DEFAULT_SELLING_BROKERAGE = os.environ.get('DEFAULT_SELLING_BROKERAGE', '')
DEFAULT_SELLING_AGENT = os.environ.get('DEFAULT_SELLING_AGENT', '')

# Security: Don't allow files to be overwritten if they have the same name
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None

# Security: This tells Django to generate Pre-Signed URLs that expire
# rather than making the S3 URLs public permanently.
AWS_QUERYSTRING_AUTH = True
AWS_QUERYSTRING_EXPIRE = 300 # Links expire in 5 minutes (300 seconds)

# Tell Django to use S3 for media files (user uploads/generated PDFs)
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    # 60 days: agents shouldn't be force-logged-out mid-transaction. The app
    # silently refreshes the access token; when the refresh token finally
    # expires it cleanly routes back to the OTP login.
    'REFRESH_TOKEN_LIFETIME': timedelta(days=60),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}
